DROP table RESEARCH.nvd_cpe;

CREATE TABLE RESEARCH.NVD_CPE
(
CVE_ID 					VARCHAR2(20 CHAR),
CPE23URI				VARCHAR2(200 char),
VULNERABLE				VARCHAR2(5 char),
VERSION_END_INCLUDING	VARCHAR2(200 CHAR),
PART					VARCHAR2(1 char),
VENDOR					VARCHAR2(200 char),
PRODUCT					VARCHAR2(200 char),
VERSION					VARCHAR2(100 char)
);
