DROP table RESEARCH.nvd_cve;

CREATE TABLE RESEARCH.NVD_CVE 
(
CVE_YEAR 				NUMBER(4), 
CVE_ID 					VARCHAR2(20 CHAR),
ASSIGNER				VARCHAR2(100 char),
CVE_DESCRIPTION 		VARCHAR2(4000 CHAR), 
CVSS_BASE_SCORE 		NUMBER(3,1), 
CVSS_VECTOR 			VARCHAR2(100 CHAR), 
CVSS_TEMPORAL_SCORE 	NUMBER(3,1), 
CVSS_TEMPORAL_VECTOR 	VARCHAR2(100 CHAR), 
EXPLOITABILITY 			NUMBER(3,1), 
IMPACT 					NUMBER(3,1), 
attackVector			VARCHAR2(20 CHAR), 
attackComplexity		VARCHAR2(20 CHAR), 
privilegesRequired		VARCHAR2(20 CHAR), 
userInteraction			VARCHAR2(20 CHAR), 
scope					VARCHAR2(20 CHAR),
confidentialityImpact   VARCHAR2(20 CHAR), 
integrityImpact			VARCHAR2(20 CHAR), 
availabilityImpact		VARCHAR2(20 CHAR), 
PUBLISHED_DATE 			DATE,
MODIFIED_DATE 			DATE,
TIER 					NUMBER(2),
AGE_IN_DAYS 			NUMBER,
SEVERITY 				VARCHAR2(20 CHAR)
);
